---
- name: Enable the supervisord service
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: "^supervisord_enable="
    line: 'supervisord_enable="YES"'
  notify:
    - Start Supervisord
