---
- name: Start Supervisord
  ansible.builtin.service:
    name: supervisord
    state: started
  register: supervisord_service_result

- name: Restart Supervisord
  ansible.builtin.service:
    name: supervisord
    state: restarted
  when: not (supervisord_service_result is defined and supervisord_service_result.changed)
